package model;
// Generated 11-abr-2014 11:31:45 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private long id;
     private String nombre;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Ciudad() {
    }

	
    public Ciudad(long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Ciudad(long id, String nombre, Set<Cliente> clientes) {
       this.id = id;
       this.nombre = nombre;
       this.clientes = clientes;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


